version: 2.1 



jobs:
  build:
    docker:
      - image: 'circleci/ruby:2.7.0'
    steps:
      - checkout
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - .
  linters:
    docker:
      - image: 'circleci/ruby:2.7.0'

    parameters:
      report_dir:
        type: string
        default: $CIRCLE_TEST_REPORTS
        description: "rubocop reports dir. default is $CIRCLE_TEST_REPORTS"
      files:
        type: string
        default: "app/**/*.rb lib/**/*.rb config/**/*.rb spec/**/*.rb script/**/*.rb"
        description: "rubocop target paths. default is app lib config spec script" 
    steps:
      - attach_workspace:
         at: .
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run Rubocop
          command: |
            mkdir -p << parameters.report_dir >>
            rubocop_reports_dir="<< parameters.report_dir >>"/rubocop
            mkdir -p $rubocop_reports_dir
            bundle exec rubocop --require rubocop-rspec --out $rubocop_reports_dir/junit.xml --format progress
          files: << parameters.files >>
      - run: 
          name: HAML Linter 
          command: |
            bundle exec haml-lint --config .haml-lint_todo.yml app/views/
workflows:
  test_all:
    jobs:
      - build
      - linters:
          requires:
            - build
