version: 2.1 

orbs:
  ruby: circleci/ruby@1.0

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
      steps:
        - checkout
        - ruby/install:
            version: '2.7'
        - ruby/install-deps
        - run: bundle instal
